### ISSUE TITLE
Remove `google-gax` dependency.

### ISSUE THREAD

**Issue by vincentpaca** [keypup-io/cloudtasker#50] opened 2022-01-18 06:34 UTC
After installing `cloudtasker v0.12.2` I got the following warning after `bundle install`:

```
The google-gax gem is officially end-of-life and will not be updated further.

If your app uses the google-gax gem, it likely is using obsolete versions of
some Google Cloud client library (google-cloud-*) gem that depends on it. We
recommend updating any such libraries that depend on google-gax. Modern Google
Cloud client libraries will depend on the gapic-common gem instead.
```

I haven't fully dug in to the code on the usages on google-gax yet but hopefully a dependency update will just work.  I can give it a shot if this wasn't already being worked on right now. If it is, is there an existing branch? Thanks in advance!

**Comment by alachaum** [comment] 2022-01-24 14:26
@vincentpaca the issue actually comes from using google-cloud-tasks v1, which cloudtasker is using at the moment.

I'll try to make a PR to address this and support google-cloud-tasks v2.

Closing as duplicate of #11

**Closed by alachaum** 2022-01-24 14:26 UTC

**Comment by vincentpaca** [comment] 2022-01-25 02:13
@alachaum ah good to know! Thank you.

**Comment by alachaum** [comment] 2022-01-25 13:53
Version `v0.13.rc2` with support for `google-cloud-tasks` v2 has been released (this means `google-gax` is no more required) 🎉
